/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import controladores.ControlNavegacion;
import javax.swing.ButtonGroup;

/**
 *
 * @author Luis Rafael Lagarda Encinas 252605
 */
public class PanelCrearSala extends javax.swing.JPanel {
    private ControlNavegacion control;
    private String dificultad;
    /**
     * Creates new form panelSala
     * @param control
     */
    public PanelCrearSala(ControlNavegacion control) {
        this.control = control;
        initComponents();
        ButtonGroup nivel = new ButtonGroup();
        nivel.add(radioBasico);
        nivel.add(radioIntermedio);
        nivel.add(radioAvanzado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSeleccionAvatar = new javax.swing.JPanel();
        panelAvatar = new javax.swing.JPanel();
        derecha = new javax.swing.JButton();
        izquierda = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        panelDatosConfigJuego1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radioIntermedio = new javax.swing.JRadioButton();
        radioAvanzado = new javax.swing.JRadioButton();
        radioBasico = new javax.swing.JRadioButton();
        txtLimiteJugador = new javax.swing.JTextField();
        txtPuntajeGanador = new javax.swing.JTextField();
        txtChorro = new javax.swing.JTextField();
        txtLlena = new javax.swing.JTextField();
        txtCentro = new javax.swing.JTextField();
        txtCuatro = new javax.swing.JTextField();
        masLM = new javax.swing.JButton();
        menLM = new javax.swing.JButton();
        menPG = new javax.swing.JButton();
        masPG = new javax.swing.JButton();
        menCH = new javax.swing.JButton();
        masCH = new javax.swing.JButton();
        masLL = new javax.swing.JButton();
        menLL = new javax.swing.JButton();
        masCT = new javax.swing.JButton();
        menCT = new javax.swing.JButton();
        menCE = new javax.swing.JButton();
        masCE = new javax.swing.JButton();
        etquetaConfiguracion = new javax.swing.JLabel();
        buttonCrearSala = new javax.swing.JButton();
        buttonVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 178, 0));

        panelSeleccionAvatar.setBackground(new java.awt.Color(217, 22, 86));

        javax.swing.GroupLayout panelAvatarLayout = new javax.swing.GroupLayout(panelAvatar);
        panelAvatar.setLayout(panelAvatarLayout);
        panelAvatarLayout.setHorizontalGroup(
            panelAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelAvatarLayout.setVerticalGroup(
            panelAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        derecha.setBackground(new java.awt.Color(217, 22, 86));
        derecha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        derecha.setForeground(new java.awt.Color(255, 255, 255));
        derecha.setText("---->");

        izquierda.setBackground(new java.awt.Color(217, 22, 86));
        izquierda.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        izquierda.setForeground(new java.awt.Color(255, 255, 255));
        izquierda.setText("<----");
        izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izquierdaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Avata");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSeleccionAvatarLayout = new javax.swing.GroupLayout(panelSeleccionAvatar);
        panelSeleccionAvatar.setLayout(panelSeleccionAvatarLayout);
        panelSeleccionAvatarLayout.setHorizontalGroup(
            panelSeleccionAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionAvatarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(217, 217, 217))
            .addGroup(panelSeleccionAvatarLayout.createSequentialGroup()
                .addGroup(panelSeleccionAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSeleccionAvatarLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(izquierda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSeleccionAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(panelAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(derecha))
                    .addGroup(panelSeleccionAvatarLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel8)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        panelSeleccionAvatarLayout.setVerticalGroup(
            panelSeleccionAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionAvatarLayout.createSequentialGroup()
                .addGroup(panelSeleccionAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSeleccionAvatarLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(derecha))
                    .addGroup(panelSeleccionAvatarLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(panelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSeleccionAvatarLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(izquierda)))
                .addGap(39, 39, 39)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatosConfigJuego1.setBackground(new java.awt.Color(217, 22, 86));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Limite de Jugadores");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Puntaje Ganador");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chorro");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cuatro Esquinas");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Centro");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Llena");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nivel");

        radioIntermedio.setBackground(new java.awt.Color(217, 22, 86));
        radioIntermedio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        radioIntermedio.setForeground(new java.awt.Color(255, 255, 255));
        radioIntermedio.setText("Intermedio");
        radioIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIntermedioActionPerformed(evt);
            }
        });

        radioAvanzado.setBackground(new java.awt.Color(217, 22, 86));
        radioAvanzado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        radioAvanzado.setForeground(new java.awt.Color(255, 255, 255));
        radioAvanzado.setText("Avanzado");
        radioAvanzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAvanzadoActionPerformed(evt);
            }
        });

        radioBasico.setBackground(new java.awt.Color(217, 22, 86));
        radioBasico.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        radioBasico.setForeground(new java.awt.Color(255, 255, 255));
        radioBasico.setText("Basico");
        radioBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBasicoActionPerformed(evt);
            }
        });

        txtLimiteJugador.setText("4");
        txtLimiteJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimiteJugadorActionPerformed(evt);
            }
        });

        txtPuntajeGanador.setText("1000");
        txtPuntajeGanador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuntajeGanadorActionPerformed(evt);
            }
        });

        txtChorro.setText("100");
        txtChorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChorroActionPerformed(evt);
            }
        });

        txtLlena.setText("100");
        txtLlena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLlenaActionPerformed(evt);
            }
        });

        txtCentro.setText("100");
        txtCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCentroActionPerformed(evt);
            }
        });

        txtCuatro.setText("100");
        txtCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuatroActionPerformed(evt);
            }
        });

        masLM.setText("+");
        masLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masLMActionPerformed(evt);
            }
        });

        menLM.setText("-");
        menLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menLMActionPerformed(evt);
            }
        });

        menPG.setText("-");
        menPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPGActionPerformed(evt);
            }
        });

        masPG.setText("+");

        menCH.setText("-");
        menCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCHActionPerformed(evt);
            }
        });

        masCH.setText("+");

        masLL.setText("+");

        menLL.setText("-");
        menLL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menLLActionPerformed(evt);
            }
        });

        masCT.setText("+");

        menCT.setText("-");
        menCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCTActionPerformed(evt);
            }
        });

        menCE.setText("-");
        menCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCEActionPerformed(evt);
            }
        });

        masCE.setText("+");

        javax.swing.GroupLayout panelDatosConfigJuego1Layout = new javax.swing.GroupLayout(panelDatosConfigJuego1);
        panelDatosConfigJuego1.setLayout(panelDatosConfigJuego1Layout);
        panelDatosConfigJuego1Layout.setHorizontalGroup(
            panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                        .addComponent(radioBasico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(radioIntermedio)
                        .addGap(71, 71, 71)
                        .addComponent(radioAvanzado))
                    .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                        .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(69, 69, 69)
                        .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                                .addComponent(txtChorro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masCH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menCH))
                            .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                                .addComponent(txtPuntajeGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masPG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menPG))
                            .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                                .addComponent(txtLimiteJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masLM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menLM))
                            .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                                .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLlena, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                                        .addComponent(masLL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(menLL))
                                    .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                                        .addComponent(masCT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(menCT))
                                    .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                                        .addComponent(masCE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(menCE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosConfigJuego1Layout.setVerticalGroup(
            panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLimiteJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masLM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menLM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPuntajeGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masPG, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menPG, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtChorro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masCH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menCH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(panelDatosConfigJuego1Layout.createSequentialGroup()
                        .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(masCE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menCE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(masCT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(menCT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLlena, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(masLL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(menLL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(53, 53, 53)
                .addGroup(panelDatosConfigJuego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioIntermedio)
                    .addComponent(radioAvanzado)
                    .addComponent(radioBasico))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        etquetaConfiguracion.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        etquetaConfiguracion.setText("Configuración");

        buttonCrearSala.setBackground(new java.awt.Color(100, 13, 95));
        buttonCrearSala.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonCrearSala.setForeground(new java.awt.Color(255, 255, 255));
        buttonCrearSala.setText("Crear Sala");
        buttonCrearSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearSalaActionPerformed(evt);
            }
        });

        buttonVolver.setBackground(new java.awt.Color(235, 91, 0));
        buttonVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonVolver.setForeground(new java.awt.Color(255, 255, 255));
        buttonVolver.setText("Volver");
        buttonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etquetaConfiguracion)
                        .addGap(475, 475, 475))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelDatosConfigJuego1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(panelSeleccionAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonVolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCrearSala)))
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(etquetaConfiguracion)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSeleccionAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatosConfigJuego1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCrearSala)
                    .addComponent(buttonVolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIntermedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioIntermedioActionPerformed

    private void radioAvanzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAvanzadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioAvanzadoActionPerformed

    private void radioBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBasicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBasicoActionPerformed

    private void buttonCrearSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCrearSalaActionPerformed

    private void buttonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVolverActionPerformed
        // TODO add your handling code here:
                if (radioBasico.isSelected()) {
                    dificultad = "Basico";
                } else if (radioIntermedio.isSelected()) {
                    dificultad = "Intemedio";
                } else if (radioAvanzado.isSelected()) {
                    dificultad = "Avanzado";
                } else {
                    System.out.print("");
                }
    }//GEN-LAST:event_buttonVolverActionPerformed

    private void txtLimiteJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimiteJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLimiteJugadorActionPerformed

    private void txtPuntajeGanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuntajeGanadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuntajeGanadorActionPerformed

    private void txtChorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChorroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChorroActionPerformed

    private void txtLlenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLlenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLlenaActionPerformed

    private void txtCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCentroActionPerformed

    private void txtCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuatroActionPerformed

    private void menLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menLMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menLMActionPerformed

    private void menPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menPGActionPerformed

    private void menCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCHActionPerformed

    private void menLLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menLLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menLLActionPerformed

    private void menCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCTActionPerformed

    private void menCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCEActionPerformed

    private void masLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masLMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masLMActionPerformed

    private void izquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izquierdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_izquierdaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCrearSala;
    private javax.swing.JButton buttonVolver;
    private javax.swing.JButton derecha;
    private javax.swing.JLabel etquetaConfiguracion;
    private javax.swing.JButton izquierda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton masCE;
    private javax.swing.JButton masCH;
    private javax.swing.JButton masCT;
    private javax.swing.JButton masLL;
    private javax.swing.JButton masLM;
    private javax.swing.JButton masPG;
    private javax.swing.JButton menCE;
    private javax.swing.JButton menCH;
    private javax.swing.JButton menCT;
    private javax.swing.JButton menLL;
    private javax.swing.JButton menLM;
    private javax.swing.JButton menPG;
    private javax.swing.JPanel panelAvatar;
    private javax.swing.JPanel panelDatosConfigJuego1;
    private javax.swing.JPanel panelSeleccionAvatar;
    private javax.swing.JRadioButton radioAvanzado;
    private javax.swing.JRadioButton radioBasico;
    private javax.swing.JRadioButton radioIntermedio;
    private javax.swing.JTextField txtCentro;
    private javax.swing.JTextField txtChorro;
    private javax.swing.JTextField txtCuatro;
    private javax.swing.JTextField txtLimiteJugador;
    private javax.swing.JTextField txtLlena;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuntajeGanador;
    // End of variables declaration//GEN-END:variables
}
