package vista;

import modelo.JugadorSubject;
import modelo.Subject;

/**
 *
 * @author pedro
 */
public class FrameJuego extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameJuego.class.getName());

    private static FrameJuego frameJuego;

    /**
     * Creates new form FrameJuego
     */
    private FrameJuego() {
        initComponents();
    }

    public static FrameJuego getInstance(){
        if(frameJuego==null){
            frameJuego = new FrameJuego();
        }
        return frameJuego;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJuego = new PanelJuego();
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelJuego, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private PanelJuego panelJuego;

    public void actualizarVista(Subject subject){
        panelJuego.actualizarVista(subject);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
