package vista;

import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;

import modelo.JugadorSubject;

/**
 *
 * @author norma
 */
public class PanelJugadorSecundario extends javax.swing.JPanel {

    private Image imagenFondo;
    private static final int ANCHO_ALTO = 80;
    private ImageIcon fotoJugador;
    
    /**
     * Creates new form PanelJugadorSecundario
     */
    public PanelJugadorSecundario() {
        setOpaque(true);
        initComponents();
        dibujarFondo();
        cargarFotoJugador();
    }

    public void setNombre(String nombre) {
        lblNombre.setText(nombre);
    }

    public void setPuntaje(int puntaje) {
        lblPuntaje.setText("Puntaje: " + puntaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPuntaje = new javax.swing.JLabel();
        panelTarjetaSecundaria1 = new vista.PanelTarjetaSecundaria();

        setMaximumSize(new java.awt.Dimension(275, 130));
        setMinimumSize(new java.awt.Dimension(275, 130));
        setPreferredSize(new java.awt.Dimension(275, 130));
        setVerifyInputWhenFocusTarget(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_alt/icon_imagen.png"))); // NOI18N
        lblFoto.setPreferredSize(new java.awt.Dimension(80, 80));
        add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 18, -1, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Adel");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 104, 85, -1));

        lblPuntaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPuntaje.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntaje.setText("Puntaje: 0");
        add(lblPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 104, -1, -1));
        add(panelTarjetaSecundaria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void dibujarFondo() {
        imagenFondo = new javax.swing.ImageIcon(getClass().getResource("/fondos/fondo_jugador_secundario.png"))
                .getImage();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (imagenFondo != null) {
            g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
        }
    }
    
    private void cargarFotoJugador(){
        fotoJugador = cargarFoto();
        lblFoto.setIcon(fotoJugador);
    }
    
    private ImageIcon cargarFoto() {
        String url = "/imagenes_alt/icon_imagen.png";
        URL recurso = getClass().getResource(url);
        if (recurso == null) {
            System.err.println("No se encontró la imagen: " + url);
        }
        ImageIcon original = new ImageIcon(recurso);
        Image imagenEscalada = original.getImage().getScaledInstance(ANCHO_ALTO, ANCHO_ALTO, Image.SCALE_SMOOTH);
        return new ImageIcon(imagenEscalada);
    }

    public void setJugador(JugadorSubject jugador){
        lblNombre.setText(jugador.getNickname());
        lblPuntaje.setText("Puntaje: "+jugador.getPuntaje());
        fotoJugador = new ImageIcon(jugador.getFoto());
        cargarFoto();
        repaint();
        revalidate();
    }

    public boolean esMismoJugador(JugadorSubject jugador){
        return lblNombre.getText().equals(jugador.getNickname());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuntaje;
    private vista.PanelTarjetaSecundaria panelTarjetaSecundaria1;
    // End of variables declaration//GEN-END:variables
}
