/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.awt.image.RescaleOp;
import javax.swing.ImageIcon;

/**
 *
 * @author Jp
 */
public class PanelCartita extends javax.swing.JPanel {

    private int numeroCarta;
    private int posicion;
    private ImageIcon iconoOriginal;
    private ImageIcon iconoHover;
    private ImageIcon iconoActual;
    private ImageIcon ficha;
    private boolean mostrarFicha = false;

    /**
     * Creates new form PanelCartita
     *
     * @param numeroCarta
     */
    public PanelCartita(int numeroCarta) {
        initComponents();

        this.numeroCarta = numeroCarta;

        iconoOriginal = cargarCarta(numeroCarta);
        iconoHover = crearBrillo(iconoOriginal, 1.2f);
        iconoActual = iconoOriginal;

        ficha = cargarFicha();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(80, 100));

        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                iconoActual = iconoHover;
                repaint();
            }

            @Override
            public void mouseExited(MouseEvent e) {
                iconoActual = iconoOriginal;
                repaint();
            }

            @Override
            public void mousePressed(MouseEvent e) {
                mostrarFicha = !mostrarFicha;
                repaint();
            }
        });
    }

    private ImageIcon cargarCarta(int numero) {
        String url = "/cartas/" + numero + ".jpeg";
        java.net.URL recurso = getClass().getResource(url);
        if (recurso == null) {
            System.err.println("No se encontró la imagen: " + url);
        }
        ImageIcon original = new ImageIcon(recurso);
        Image imagenEscalada = original.getImage().getScaledInstance(80, 100, Image.SCALE_SMOOTH);
        return new ImageIcon(imagenEscalada);
    }

    private ImageIcon cargarFicha() {
        String url = "/otros/ficha.png";
        java.net.URL recurso = getClass().getResource(url);
        if (recurso == null) {
            System.err.println("No se encontró la ficha: " + url);
            return null;
        }
        ImageIcon original = new ImageIcon(recurso);
        Image imagenEscalada = original.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
        return new ImageIcon(imagenEscalada);
    }

    private ImageIcon crearBrillo(ImageIcon icono, float factor) {
        Image img = icono.getImage();
        BufferedImage buff = new BufferedImage(
                img.getWidth(null),
                img.getHeight(null),
                BufferedImage.TYPE_INT_ARGB
        );
        buff.getGraphics().drawImage(img, 0, 0, null);

        RescaleOp op = new RescaleOp(factor, 0, null);
        op.filter(buff, buff);

        return new ImageIcon(buff);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (iconoActual != null) {
            g.drawImage(iconoActual.getImage(), 0, 0, getWidth(), getHeight(), this);
        }

        if (mostrarFicha && ficha != null) {
            int x = (getWidth() - ficha.getIconWidth()) / 2;
            int y = (getHeight() - ficha.getIconHeight()) / 2;
            g.drawImage(ficha.getImage(), x, y, this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
