package vista;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;

import modelo.*;

/**
 *
 * @author pedro
 */
public class PanelJuego extends javax.swing.JPanel {

    private Image imagenFondo;
    private List<PanelJugadorSecundario> panelesJugadoresSecundarios;

    /**
     * Creates new form PanelJuego
     */
    public PanelJuego() {
        initComponents();
        dibujarFondo();

        panelesJugadoresSecundarios = new ArrayList<>();
        botonCuatroEsquinas.setNombreJugada("Cuatro esquinas");
        botonChorro.setNombreJugada("Chorro");
        botonCentro.setNombreJugada("Centro");
        botonLlena.setNombreJugada("Llena");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAbandonar = new javax.swing.JButton();
        panelJugadorPrincipal = new vista.PanelJugadorPrincipal();
        botonCuatroEsquinas = new vista.BotonJugada();
        botonChorro = new vista.BotonJugada();
        botonCentro = new vista.BotonJugada();
        botonLlena = new vista.BotonJugada();
        panelContenedorSecundarios = new javax.swing.JPanel();
        panelJugadorSecundario2 = new vista.PanelJugadorSecundario();
        panelTarjeta = new vista.PanelTarjeta();
        panelContenedorCantador = new javax.swing.JPanel();
        panelCartaCantador = new vista.PanelCartita();
        lblCarta = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1336, 768));
        setMinimumSize(new java.awt.Dimension(1336, 768));
        setPreferredSize(new java.awt.Dimension(1336, 768));

        botonAbandonar.setBackground(new java.awt.Color(235, 91, 0));
        botonAbandonar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonAbandonar.setForeground(new java.awt.Color(255, 255, 255));
        botonAbandonar.setText("Abandonar");
        botonAbandonar.setFocusPainted(false);

        botonCuatroEsquinas.setRequestFocusEnabled(false);

        panelContenedorSecundarios.setBackground(new java.awt.Color(255, 178, 0));
        panelContenedorSecundarios.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 29, 0));
        panelContenedorSecundarios.add(panelJugadorSecundario2);

        panelContenedorCantador.setBackground(new java.awt.Color(255, 255, 255));

        panelCartaCantador.setToolTipText("Carta Cantada");

        javax.swing.GroupLayout panelContenedorCantadorLayout = new javax.swing.GroupLayout(panelContenedorCantador);
        panelContenedorCantador.setLayout(panelContenedorCantadorLayout);
        panelContenedorCantadorLayout.setHorizontalGroup(
            panelContenedorCantadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorCantadorLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(panelCartaCantador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        panelContenedorCantadorLayout.setVerticalGroup(
            panelContenedorCantadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorCantadorLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(panelCartaCantador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        lblCarta.setBackground(new java.awt.Color(0, 0, 0));
        lblCarta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCarta.setText("Carta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(panelContenedorSecundarios, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelJugadorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAbandonar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addComponent(panelTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lblCarta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(panelContenedorCantador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(botonCuatroEsquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonChorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(botonCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(botonLlena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panelContenedorSecundarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(panelJugadorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(botonAbandonar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblCarta)
                        .addGap(13, 13, 13)
                        .addComponent(panelContenedorCantador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(botonCuatroEsquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonChorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(botonLlena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dibujarFondo() {
        imagenFondo = new javax.swing.ImageIcon(getClass().getResource("/fondos/fondoPantalla.png")).getImage();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (imagenFondo != null) {
            g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
        }
    }

    public void actualizarVista(Subject subject){
        actualizarJugador(subject);
    }

    
    private void actualizarJugador(Subject subject){
        if(subject instanceof JugadorSubject){
            JugadorSubject jugador = (JugadorSubject) subject;
            for(PanelJugadorSecundario panel: panelesJugadoresSecundarios){
                if(panel.esMismoJugador(jugador)){
                     panel.actualizarTarjetaAbstracta(jugador);
                }
            }
            if(panelJugadorPrincipal.esMismoJugador(jugador)){
                panelTarjeta.actualizarFichas(jugador.getTarjeta());
            }
        }
    }
    
    public void setJugadorPrincipal(JugadorSubject jugador) {
        panelJugadorPrincipal.setJugador(jugador);
        repaint();
        revalidate();
    }

    public void agregarJugadorSecundario(JugadorSubject jugador) {
        PanelJugadorSecundario panel = new PanelJugadorSecundario();
        panel.setJugador(jugador);
        this.panelesJugadoresSecundarios.add(panel);
        actualizarPanelesSecundarios();
        repaint();
        revalidate();
    }

    private void actualizarPanelesSecundarios(){
        panelContenedorSecundarios.removeAll();
        for(PanelJugadorSecundario panel : panelesJugadoresSecundarios){
            panelContenedorSecundarios.add(panel);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbandonar;
    private vista.BotonJugada botonCentro;
    private vista.BotonJugada botonChorro;
    private vista.BotonJugada botonCuatroEsquinas;
    private vista.BotonJugada botonLlena;
    private javax.swing.JLabel lblCarta;
    private vista.PanelCartita panelCartaCantador;
    private javax.swing.JPanel panelContenedorCantador;
    private javax.swing.JPanel panelContenedorSecundarios;
    private vista.PanelJugadorPrincipal panelJugadorPrincipal;
    private vista.PanelJugadorSecundario panelJugadorSecundario2;
    private vista.PanelTarjeta panelTarjeta;
    // End of variables declaration//GEN-END:variables
}
