package vista;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;

/**
 *
 * @author pedro
 */
public class PanelJuego extends javax.swing.JPanel {

    private Image imagenFondo;

    /**
     * Creates new form PanelJuego
     */
    public PanelJuego() {
        initComponents();

        dibujarFondo();
        ponerTarjeta();

        //por mientras*
        panelJugadorSecundario1.setNombre("Adel");
        panelJugadorSecundario1.setPuntaje(10);

        panelJugadorSecundario2.setNombre("Denise");
        panelJugadorSecundario2.setPuntaje(500);

        panelJugadorSecundario3.setNombre("Fernando");
        panelJugadorSecundario3.setPuntaje(100);
        
        botonCuatroEsquinas.setNombreJugada("Cuatro esquinas");
        botonChorro.setNombreJugada("Chorro");
        botonCentro.setNombreJugada("Centro");
        botonLlena.setNombreJugada("Llena");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonJugada4 = new vista.BotonJugada();
        jButton1 = new javax.swing.JButton();
        panelJugadorPrincipal2 = new vista.PanelJugadorPrincipal();
        PanelContenedorTarjeta = new javax.swing.JPanel();
        panelJugadorSecundario1 = new vista.PanelJugadorSecundario();
        panelJugadorSecundario2 = new vista.PanelJugadorSecundario();
        panelJugadorSecundario3 = new vista.PanelJugadorSecundario();
        botonCuatroEsquinas = new vista.BotonJugada();
        botonChorro = new vista.BotonJugada();
        botonCentro = new vista.BotonJugada();
        botonLlena = new vista.BotonJugada();

        setMaximumSize(new java.awt.Dimension(1336, 768));
        setMinimumSize(new java.awt.Dimension(1336, 768));
        setPreferredSize(new java.awt.Dimension(1336, 768));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(235, 91, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Abandonar");
        jButton1.setFocusPainted(false);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 574, 206, 53));
        add(panelJugadorPrincipal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        PanelContenedorTarjeta.setBackground(new java.awt.Color(204, 204, 204));
        PanelContenedorTarjeta.setMinimumSize(new java.awt.Dimension(400, 533));
        PanelContenedorTarjeta.setPreferredSize(new java.awt.Dimension(400, 533));
        PanelContenedorTarjeta.setLayout(new java.awt.BorderLayout());
        add(PanelContenedorTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 204, -1, -1));
        add(panelJugadorSecundario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 148));
        add(panelJugadorSecundario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, 148));
        add(panelJugadorSecundario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, 148));
        add(botonCuatroEsquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 570, -1, -1));
        add(botonChorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 630, -1, -1));
        add(botonCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 630, -1, 50));
        add(botonLlena, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 690, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void dibujarFondo() {
        imagenFondo = new javax.swing.ImageIcon(getClass().getResource("/fondos/fondoPantalla.png")).getImage();
    }

    private void ponerTarjeta() {
        PanelTarjeta panelTarjeta = new PanelTarjeta();
        PanelContenedorTarjeta.add(panelTarjeta, BorderLayout.CENTER);
        revalidate();
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (imagenFondo != null) {
            g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedorTarjeta;
    private vista.BotonJugada botonCentro;
    private vista.BotonJugada botonChorro;
    private vista.BotonJugada botonCuatroEsquinas;
    private vista.BotonJugada botonJugada4;
    private vista.BotonJugada botonLlena;
    private javax.swing.JButton jButton1;
    private vista.PanelJugadorPrincipal panelJugadorPrincipal2;
    private vista.PanelJugadorSecundario panelJugadorSecundario1;
    private vista.PanelJugadorSecundario panelJugadorSecundario2;
    private vista.PanelJugadorSecundario panelJugadorSecundario3;
    // End of variables declaration//GEN-END:variables
}
