/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.awt.image.RescaleOp;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Jp
 */
public class PanelCartita extends javax.swing.JPanel {

    private static final int CARTA_ANCHO = 78;
    private static final int CARTA_ALTO = 128;
    private static final int FICHA_ANCHO = 50;
    private static final int FICHA_ALTO = 50;

    private static final float FACTOR_BRILLO = 1.2f;

    private int numeroCarta;
    private int posicion;
    private ImageIcon iconoOriginal;
    private ImageIcon iconoHover;
    private ImageIcon iconoActual;
    private JLabel ficha;

    /**
     * Creates new form PanelCartita
     *
     * @param numeroCarta
     */
    public PanelCartita(int numeroCarta) {
        initComponents();
        this.numeroCarta = numeroCarta;
        iniciar();
    }

    private void iniciar() {
        iconoOriginal = cargarCarta(numeroCarta);
        iconoHover = crearBrillo(iconoOriginal, FACTOR_BRILLO);
        ficha = cargarFicha();
        iconoActual = iconoOriginal;
        agregarEventosMouse();
    }

    private void agregarEventosMouse() {
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                iconoActual = iconoHover;
                repaint();
            }

            @Override
            public void mouseExited(MouseEvent e) {
                iconoActual = iconoOriginal;
                repaint();
            }

            @Override
            public void mousePressed(MouseEvent e) {
                if (ficha != null && ficha.getParent() == null) {
                    int x = (getWidth() - FICHA_ANCHO) / 2;
                    int y = (getHeight() - FICHA_ALTO) / 2;
                    ficha.setBounds(x, y, FICHA_ANCHO, FICHA_ALTO);
                    add(ficha);
                    revalidate();
                    repaint();
                }
            }
        });
    }

    private ImageIcon cargarCarta(int numero) {
        String url = "/cartas/" + numero + ".jpeg";
        URL recurso = getClass().getResource(url);
        if (recurso == null) {
            System.err.println("No se encontró la imagen: " + url);
        }
        ImageIcon original = new ImageIcon(recurso);
        Image imagenEscalada = original.getImage().getScaledInstance(CARTA_ANCHO, CARTA_ALTO, Image.SCALE_SMOOTH);
        return new ImageIcon(imagenEscalada);
    }

    private JLabel cargarFicha() {
        String url = "/otros/ficha.png";
        URL recurso = getClass().getResource(url);
        if (recurso == null) {
            System.err.println("No se encontró la ficha: " + url);
        }
        ImageIcon original = new ImageIcon(recurso);
        Image imagenEscalada = original.getImage().getScaledInstance(FICHA_ANCHO, FICHA_ALTO, Image.SCALE_SMOOTH);
        return new JLabel(new ImageIcon(imagenEscalada));
    }

    private ImageIcon crearBrillo(ImageIcon icono, float factor) {
        Image img = icono.getImage();
        BufferedImage buff = new BufferedImage(
                img.getWidth(null),
                img.getHeight(null),
                BufferedImage.TYPE_INT_ARGB
        );
        buff.getGraphics().drawImage(img, 0, 0, null);

        RescaleOp op = new RescaleOp(factor, 0, null);
        op.filter(buff, buff);

        return new ImageIcon(buff);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (iconoActual != null) {
            g.drawImage(iconoActual.getImage(), 0, 0, getWidth(), getHeight(), this);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new Dimension(CARTA_ANCHO, CARTA_ALTO));
        setOpaque(false);
        setPreferredSize(new Dimension(CARTA_ANCHO, CARTA_ALTO));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
