/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import enums.Pantalla;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import modelo.PantallaActualSubject;
import modelo.SalaSubject;
import util.Subject;
import vista.PanelConfiguracionJuego;
import vista.PanelConfiguracionUsuario;
import vista.PanelParametrosPartida;
import vista.PanelMenu;
import vista.PanelSalaEspera;

/**
 *
 * @author Jp
 */
public class FrameConfiguracion extends JFrame {

    private CardLayout cardLayout;
    private PanelConfiguracionUsuario panelConfiguracionUsuario = new PanelConfiguracionUsuario();
    private PanelConfiguracionJuego panelConfiguracionPartida = new PanelConfiguracionJuego();
    private PanelSalaEspera panelSalaEspera = new PanelSalaEspera();
    private PanelMenu panelMenu = new PanelMenu();
    private JPanel panelContenedor;
    private static FrameConfiguracion instancia;

    /**
     * Creates new form VentanaPrincipal
     *
     */
    private FrameConfiguracion() {
        iniciarVentana();
        initComponents();
        configurarCardLayout();
    }

    public static FrameConfiguracion getInstancia() {
        if (instancia == null) {
            instancia = new FrameConfiguracion();
        }
        return instancia;
    }

    public void configurarCardLayout() {
        cargarPantallas();
        cardLayout.show(panelContenedor, Pantalla.MENU.getNombre());
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    private void cargarPantallas() {
        panelContenedor.add(panelMenu, Pantalla.MENU.getNombre());
        panelContenedor.add(panelConfiguracionUsuario, Pantalla.CONFIGURAR_USUARIO.getNombre());
        panelContenedor.add(panelConfiguracionPartida, Pantalla.CONFIGURAR_PARTIDA.getNombre());
        panelContenedor.add(panelSalaEspera, Pantalla.SALA_ESPERA.getNombre());

        panelConfiguracionUsuario.configurarFramePadre(this);
    }

    private void iniciarVentana() {
        setIconImage();
        setLayout();
    }

    private void setLayout() {
        setLayout(new java.awt.BorderLayout()); // <-- Cambia el layout del JFrame
        cardLayout = new CardLayout();
        panelContenedor = new JPanel(cardLayout);
        add(panelContenedor, java.awt.BorderLayout.CENTER);
    }

    private void setIconImage() {
        try {
            setIconImage(new ImageIcon(getClass().getResource("/cartas/1.jpeg")).getImage());
        } catch (NullPointerException e) {
            System.err.println("Icono no encontrado: /cartas/1.jpeg");
        }
    }

    /**
     * Metodo para actualizar la vista del jugador.
     *
     * @param subject representacion del sujeto.
     */
    public void actualizarVista(Subject subject) {
        if (subject instanceof PantallaActualSubject pantalla) {
            Pantalla pantallaActual = pantalla.getPantallaActual();

            cardLayout.show(panelContenedor, pantallaActual.getNombre());

            if (pantallaActual == Pantalla.SALA_ESPERA) {
                panelSalaEspera.configurarModoJugadorUnido();
            } else if (pantallaActual == Pantalla.SALA_ESPERA_NO_UNIDO) {
                panelSalaEspera.configurarModoJugadorNoUnido();
            }
        }

        panelConfiguracionUsuario.actualizarVista(subject);

        if (subject instanceof SalaSubject sala) {
            panelSalaEspera.actualizarVista(subject);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loteria Mexicana");
        setMinimumSize(new java.awt.Dimension(1336, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
