/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Jp
 */
public class VentanaPrincipal extends JFrame {

    private CardLayout cardLayout;
    private JPanel panelContenedor;

    /**
     * Creates new form VentanaPrincipal
     *
     */
    public VentanaPrincipal() {
        iniciarVentana();
        initComponents();
    }

    public CardLayout getCardLayout() {
        return cardLayout;
    }

    public JPanel getPanelContenedor() {
        return panelContenedor;
    }

    private void iniciarVentana() {
        setIconImage();
        setLayout();
    }

    private void setLayout() {
        setLayout(new java.awt.BorderLayout()); // <-- Cambia el layout del JFrame
        cardLayout = new CardLayout();
        panelContenedor = new JPanel(cardLayout);
        add(panelContenedor,java.awt.BorderLayout.CENTER);
    }

    private void setIconImage() {
        try {
            setIconImage(new ImageIcon(getClass().getResource("/cartas/1.jpeg")).getImage());
        } catch (NullPointerException e) {
            System.err.println("Icono no encontrado: /cartas/1.jpeg");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loteria Mexicana");
        setMaximumSize(new java.awt.Dimension(1336, 768));
        setMinimumSize(new java.awt.Dimension(1336, 768));
        setPreferredSize(new java.awt.Dimension(1336, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
