package vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author Alici
 */
public class PanelConfigurarNombreUsuario extends javax.swing.JPanel {

    private Image iconFondo;

    /**
     * Creates new form PanelConfigurarNombreUsuario
     */
    public PanelConfigurarNombreUsuario() {
        obtenerFondo();
        initComponents();
    }

    private void obtenerFondo() {
        iconFondo = new ImageIcon(getClass().getResource("/fondos/fondo_nombreUsuario.png")).getImage();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (iconFondo != null) {
            g.drawImage(iconFondo, 0, 0, getWidth(), getHeight(), this);
        }
    }

    public void reset() {
        txtNombreUsuario.setText("");
    }

    public String obtenerNombreIngresado() {
        return txtNombreUsuario.getText().trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreUsuario = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 178, 0));
        setMaximumSize(new java.awt.Dimension(548, 292));
        setMinimumSize(new java.awt.Dimension(548, 292));

        txtNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNombreUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreUsuario.setMaximumSize(new java.awt.Dimension(448, 55));
        txtNombreUsuario.setMinimumSize(new java.awt.Dimension(448, 55));
        txtNombreUsuario.setPreferredSize(new java.awt.Dimension(448, 55));
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
