/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author norma
 */
public class PanelSalaEspera extends javax.swing.JPanel {

    /**
     * Creates new form PanelSalaEspera
     */
    public PanelSalaEspera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSala = new javax.swing.JLabel();
        panelListaJugadores1 = new vista.PanelListaJugadores();
        btnAbandonarSala = new javax.swing.JButton();
        lblNivel = new javax.swing.JLabel();
        labelNivel = new javax.swing.JLabel();
        lblEspera = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 178, 0));

        lblSala.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblSala.setText("Sala");

        btnAbandonarSala.setBackground(new java.awt.Color(235, 91, 0));
        btnAbandonarSala.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAbandonarSala.setForeground(new java.awt.Color(255, 255, 255));
        btnAbandonarSala.setText("Abandonar Sala");
        btnAbandonarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarSalaActionPerformed(evt);
            }
        });

        lblNivel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNivel.setText("Nivel");

        labelNivel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNivel.setText("Básico");

        lblEspera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEspera.setText("Esperando a que inicice la partida...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelListaJugadores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNivel)
                                    .addComponent(labelNivel)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAbandonarSala)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, Short.MAX_VALUE)
                                .addComponent(lblEspera))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(lblSala)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblSala)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panelListaJugadores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblNivel)
                        .addGap(18, 18, 18)
                        .addComponent(labelNivel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbandonarSala)
                    .addComponent(lblEspera))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbandonarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbandonarSalaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonarSala;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JLabel lblEspera;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblSala;
    private vista.PanelListaJugadores panelListaJugadores1;
    // End of variables declaration//GEN-END:variables
}
