/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import dtos.JugadorSalaEsperaDTO;
import java.awt.GridLayout;
import java.util.List;

/**
 *
 * @author norma
 */
public class PanelListaJugadores extends javax.swing.JPanel {

    /**
     * Creates new form PanelListaJugadores
     */
    public PanelListaJugadores() {
        initComponents();
        pnlContenedorLista.setLayout(new GridLayout(1, 0, 10, 0)); 
    }
    
    public void actualizarListaJugadores(List<JugadorSalaEsperaDTO> jugadores, int limiteMaximo) {
        pnlContenedorLista.removeAll();

        for (JugadorSalaEsperaDTO jugador : jugadores) {
            PanelJugadorIndividual panelJugador = new PanelJugadorIndividual();
            panelJugador.configurarJugador(jugador); 
            pnlContenedorLista.add(panelJugador);
        }

        lblCantidadJugadores.setText("(" + jugadores.size() + "/" + limiteMaximo + ")"); 

        pnlContenedorLista.revalidate();
        pnlContenedorLista.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedorLista = new javax.swing.JPanel();
        lblJugadores = new javax.swing.JLabel();
        lblCantidadJugadores = new javax.swing.JLabel();

        setBackground(new java.awt.Color(217, 22, 86));

        pnlContenedorLista.setBackground(new java.awt.Color(225, 45, 104));

        javax.swing.GroupLayout pnlContenedorListaLayout = new javax.swing.GroupLayout(pnlContenedorLista);
        pnlContenedorLista.setLayout(pnlContenedorListaLayout);
        pnlContenedorListaLayout.setHorizontalGroup(
            pnlContenedorListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        pnlContenedorListaLayout.setVerticalGroup(
            pnlContenedorListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        lblJugadores.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblJugadores.setForeground(new java.awt.Color(255, 255, 255));
        lblJugadores.setText("Jugadores ");

        lblCantidadJugadores.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCantidadJugadores.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadJugadores.setText("(1/2)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlContenedorLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJugadores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCantidadJugadores)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugadores)
                    .addComponent(lblCantidadJugadores))
                .addGap(18, 18, 18)
                .addComponent(pnlContenedorLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCantidadJugadores;
    private javax.swing.JLabel lblJugadores;
    private javax.swing.JPanel pnlContenedorLista;
    // End of variables declaration//GEN-END:variables
}
