/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import dtos.aplicacion.JugadorSalaEsperaDTO;
import java.util.List;

import javax.swing.JScrollPane;

/**
 *
 * @author norma
 */
public class PanelListaJugadores extends javax.swing.JPanel {

    /**
     * Creates new form PanelListaJugadores
     */
    /**
     * Creates new form PanelListaJugadores
     */
    public PanelListaJugadores() {
        initComponents();
    }

    public void actualizarListaJugadores(List<JugadorSalaEsperaDTO> jugadores, int limiteMaximo) {
        pnlContenedorLista.removeAll();

        for (JugadorSalaEsperaDTO jugador : jugadores) {
            PanelJugadorIndividual panelJugador = new PanelJugadorIndividual();
            panelJugador.configurarJugador(jugador);
            
            pnlContenedorLista.add(panelJugador);
        }

        lblCantidadJugadores.setText("(" + jugadores.size() + "/" + limiteMaximo + ")");

        pnlContenedorLista.revalidate();
        pnlContenedorLista.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJugadores = new javax.swing.JLabel();
        lblCantidadJugadores = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        pnlContenedorLista = new javax.swing.JPanel();

        setBackground(new java.awt.Color(217, 22, 86));

        lblJugadores.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblJugadores.setForeground(new java.awt.Color(255, 255, 255));
        lblJugadores.setText("Jugadores ");

        lblCantidadJugadores.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCantidadJugadores.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadJugadores.setText("(1/2)");

        scroll.setBackground(new java.awt.Color(255, 153, 153));
        scroll.setBorder(null);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlContenedorLista.setBackground(new java.awt.Color(217, 22, 86));
        pnlContenedorLista.setLayout(new javax.swing.BoxLayout(pnlContenedorLista, javax.swing.BoxLayout.Y_AXIS));
        scroll.setViewportView(pnlContenedorLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJugadores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCantidadJugadores)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugadores)
                    .addComponent(lblCantidadJugadores))
                .addGap(18, 18, 18)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCantidadJugadores;
    private javax.swing.JLabel lblJugadores;
    private javax.swing.JPanel pnlContenedorLista;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
