package vista;

import dtos.aplicacion.ConfiguracionJuegoDTO;
import enums.JugadasDisponibles;
import enums.TipoNivel;
import java.awt.Graphics;
import java.awt.Image;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Alici
 */
public class PanelParametrosPartida extends javax.swing.JPanel {

    private Image iconFondo;

    /**
     * Creates new form PanelConfigurarPartida
     */
    public PanelParametrosPartida() {
        obtenerFondo();
        initComponents();
        configurarSpinners();
        configurarRadioButtons();
        
        radioBtnNivelBasico.setSelected(true);
    }

    private void configurarSpinners() {
        SpinnerNumberModel modeloPuntajeMaximo = new SpinnerNumberModel(500, 0, 100000000, 100);
        SpinnerNumberModel modeloLlena = new SpinnerNumberModel(200, 0, 100000000, 100);
        SpinnerNumberModel modeloChorro = new SpinnerNumberModel(100, 0, 100000000, 100);
        SpinnerNumberModel modeloCuatroEsquinas = new SpinnerNumberModel(100, 0, 100000000, 100);
        SpinnerNumberModel modeloCentro = new SpinnerNumberModel(100, 0, 100000000, 100);

        SpinnerNumberModel modeloLimiteJugadores = new SpinnerNumberModel(2, 2, 4, 1);

        spinnerLimiteJugadores.setModel(modeloLimiteJugadores);
        spinnerCentro.setModel(modeloCentro);
        spinnerPuntajeMaximo.setModel(modeloPuntajeMaximo);
        spinnerChorro.setModel(modeloChorro);
        spinnerCuatroEsquinas.setModel(modeloCuatroEsquinas);
        spinnerLlena.setModel(modeloLlena);
    }

    private void configurarRadioButtons() {
        radioBtnNivelBasico.setActionCommand(TipoNivel.BASICO.name());
        radioBtnNivelIntermedio.setActionCommand(TipoNivel.INTERMEDIO.name());
        radioButtonNivelDificil.setActionCommand(TipoNivel.DIFICIL.name());
    }

    private void obtenerFondo() {
        iconFondo = new ImageIcon(getClass().getResource("/fondos/fondo_configuracionSala.png")).getImage();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (iconFondo != null) {
            g.drawImage(iconFondo, 0, 0, getWidth(), getHeight(), this);
        }
    }

    public ConfiguracionJuegoDTO obtenerConfiguracion() {
        ConfiguracionJuegoDTO configuracionJuegoDTO = new ConfiguracionJuegoDTO();
        configuracionJuegoDTO.setLimiteJugadores((int) spinnerLimiteJugadores.getValue());
        configuracionJuegoDTO.setPuntajeMax((int) spinnerPuntajeMaximo.getValue());
        configuracionJuegoDTO.setDificultad(nivelSeleccionado());
        configuracionJuegoDTO.setPuntajes(puntajes());
        return configuracionJuegoDTO;
    }

    private Map<JugadasDisponibles, Integer> puntajes() {
        Map<JugadasDisponibles, Integer> puntajes = new HashMap<>();
        puntajes.put(JugadasDisponibles.LLENA, (Integer) spinnerLlena.getValue());
        puntajes.put(JugadasDisponibles.CENTRO, (Integer) spinnerCentro.getValue());
        puntajes.put(JugadasDisponibles.CUATROESQUINAS, (Integer) spinnerCuatroEsquinas.getValue());
        puntajes.put(JugadasDisponibles.CHORRO, (Integer) spinnerChorro.getValue());
        return puntajes;
    }

    private TipoNivel nivelSeleccionado() {
        ButtonModel modelo = buttonGroupNivel.getSelection();
        if (modelo == null) {
            return null;
        }
        TipoNivel nivelSeleccionado = null;
        String actionCommand = modelo.getActionCommand();
        if (modelo.getActionCommand().equals(TipoNivel.BASICO.name())) {
            nivelSeleccionado = TipoNivel.BASICO;
        }
        if (modelo.getActionCommand().equals(TipoNivel.INTERMEDIO.name())) {
            nivelSeleccionado = TipoNivel.INTERMEDIO;
        }
        if (modelo.getActionCommand().equals(TipoNivel.DIFICIL.name())) {
            nivelSeleccionado = TipoNivel.DIFICIL;
        }

        return nivelSeleccionado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupNivel = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        radioButtonNivelDificil = new javax.swing.JRadioButton();
        radioBtnNivelIntermedio = new javax.swing.JRadioButton();
        radioBtnNivelBasico = new javax.swing.JRadioButton();
        spinnerLlena = new javax.swing.JSpinner();
        spinnerLimiteJugadores = new javax.swing.JSpinner();
        spinnerPuntajeMaximo = new javax.swing.JSpinner();
        spinnerChorro = new javax.swing.JSpinner();
        spinnerCuatroEsquinas = new javax.swing.JSpinner();
        spinnerCentro = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(255, 178, 0));
        setMaximumSize(new java.awt.Dimension(1160, 527));
        setMinimumSize(new java.awt.Dimension(1160, 527));
        setPreferredSize(new java.awt.Dimension(1160, 527));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Llena");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nivel de velocidad");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Límite de jugadores");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Puntaje ganador");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Chorro");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cuatro esquinas");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Centro");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Puntajes por jugada");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        radioButtonNivelDificil.setBackground(new java.awt.Color(217, 22, 86));
        buttonGroupNivel.add(radioButtonNivelDificil);
        radioButtonNivelDificil.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        radioButtonNivelDificil.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonNivelDificil.setText("Difícil");
        add(radioButtonNivelDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 280, -1, -1));

        radioBtnNivelIntermedio.setBackground(new java.awt.Color(217, 22, 86));
        buttonGroupNivel.add(radioBtnNivelIntermedio);
        radioBtnNivelIntermedio.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        radioBtnNivelIntermedio.setForeground(new java.awt.Color(255, 255, 255));
        radioBtnNivelIntermedio.setText("Intermedio");
        radioBtnNivelIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnNivelIntermedioActionPerformed(evt);
            }
        });
        add(radioBtnNivelIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, -1));

        radioBtnNivelBasico.setBackground(new java.awt.Color(217, 22, 86));
        buttonGroupNivel.add(radioBtnNivelBasico);
        radioBtnNivelBasico.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        radioBtnNivelBasico.setForeground(new java.awt.Color(255, 255, 255));
        radioBtnNivelBasico.setText("Básico");
        radioBtnNivelBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnNivelBasicoActionPerformed(evt);
            }
        });
        add(radioBtnNivelBasico, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));
        add(spinnerLlena, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 100, 30));
        add(spinnerLimiteJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 100, 30));
        add(spinnerPuntajeMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 100, 30));
        add(spinnerChorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 100, 30));
        add(spinnerCuatroEsquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 100, 30));
        add(spinnerCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void radioBtnNivelBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnNivelBasicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnNivelBasicoActionPerformed

    private void radioBtnNivelIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnNivelIntermedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnNivelIntermedioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton radioBtnNivelBasico;
    private javax.swing.JRadioButton radioBtnNivelIntermedio;
    private javax.swing.JRadioButton radioButtonNivelDificil;
    private javax.swing.JSpinner spinnerCentro;
    private javax.swing.JSpinner spinnerChorro;
    private javax.swing.JSpinner spinnerCuatroEsquinas;
    private javax.swing.JSpinner spinnerLimiteJugadores;
    private javax.swing.JSpinner spinnerLlena;
    private javax.swing.JSpinner spinnerPuntajeMaximo;
    // End of variables declaration//GEN-END:variables
}
