/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Alici
 */
public class PanelAvatar extends javax.swing.JPanel {

    private ImageIcon iconoActual;
    private static final int ANCHO_ICON = 140;
    private static final int ALTO_ICON = 140;

    /**
     * Creates new form PanelAvatar
     */
    public PanelAvatar() {
        actualizarAvatar(1);
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (iconoActual != null) {
            g.drawImage(iconoActual.getImage(), 0, 0, getWidth(), getHeight(), this);
        }
    }

    private ImageIcon cargarAvatar(int numero) {
        String url = "/avatars/" + numero + ".jpg";
        URL recurso = getClass().getResource(url);
        if (recurso == null) {
            System.err.println("No se encontró la imagen: " + url);
        }
        ImageIcon original = new ImageIcon(recurso);
        Image imagenEscalada = original.getImage().getScaledInstance(ANCHO_ICON, ALTO_ICON,
                Image.SCALE_SMOOTH);

        return new ImageIcon(imagenEscalada);
    }

    public void actualizarAvatar(int avatar) {
        iconoActual = cargarAvatar(avatar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(140, 140));
        setMinimumSize(new java.awt.Dimension(140, 140));
        setPreferredSize(new java.awt.Dimension(140, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
