/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import Modal.MensajeDialog;
import controladores.ControlesConfiguracionFactory;
import dtos.aplicacion.ConfiguracionJuegoDTO;
import enums.TipoConfiguracion;
import enums.TipoMensajePantalla;
import java.awt.Frame;
import modelo.MensajeSubject;
import util.Subject;

/**
 *
 * @author Alici
 */
public class PanelConfiguracionJuego extends javax.swing.JPanel {

    private Frame ventanaPrincipal;

    /**
     * Creates new form PanelConfiguracionJuego
     */
    public PanelConfiguracionJuego() {
        initComponents();
    }

    public void configurarFramePadre(Frame ventanaPadre) {
        ventanaPrincipal = ventanaPadre;
    }

    public void actualizarVista(Subject subject) {
        actualizarMensaje(subject);
        repaint();
        revalidate();
    }

    private void mandarConfiguracionSala() {
        ConfiguracionJuegoDTO configuracionJuegoDTO = panelParametrosPartida.obtenerConfiguracion();
        ControlesConfiguracionFactory controles = ControlesConfiguracionFactory.getInstance();
        controles.getControlConfiguracion().configurarPartida(configuracionJuegoDTO);
    }

    private void actualizarMensaje(Subject subject) {
        if (subject instanceof MensajeSubject validacion) {
            if (validacion.getTipoMensaje() == TipoMensajePantalla.VALIDACION_CONFIG_PARTIDA) {
                MensajeDialog mensajeDialog = new MensajeDialog(ventanaPrincipal, true);
                mensajeDialog.setDatos(validacion.getTitulo(), validacion.getMensaje());
                mensajeDialog.mostrarDialogo();

                if (validacion.isExitoso()) {
                    ControlesConfiguracionFactory controles = ControlesConfiguracionFactory.getInstance();
                    controles.getControlAplicacion().mostrarPanelSalaEsperaJuego();
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnCrearSala = new javax.swing.JButton();
        panelParametrosPartida = new vista.PanelParametrosPartida();

        setBackground(new java.awt.Color(255, 178, 0));
        setMaximumSize(new java.awt.Dimension(1336, 768));
        setMinimumSize(new java.awt.Dimension(1336, 768));
        setPreferredSize(new java.awt.Dimension(1336, 768));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Configuración de partida");

        btnCrearSala.setBackground(new java.awt.Color(100, 13, 95));
        btnCrearSala.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCrearSala.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearSala.setText("Crear sala");
        btnCrearSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCrearSala, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelParametrosPartida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(panelParametrosPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearSala, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSalaActionPerformed
        mandarConfiguracionSala();
    }//GEN-LAST:event_btnCrearSalaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearSala;
    private javax.swing.JLabel lblTitulo;
    private vista.PanelParametrosPartida panelParametrosPartida;
    // End of variables declaration//GEN-END:variables
}
