/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controladores.ControlesConfiguracionFactory;
import dtos.aplicacion.JugadorSalaEsperaDTO;
import enums.TipoNivel;
import java.util.List;
import modelo.SalaSubject;
import util.Subject;

/**
 *
 * @author norma
 */
public class PanelSalaEspera extends javax.swing.JPanel {

    /**
     * Creates new form PanelSalaEspera
     */
    public PanelSalaEspera() {
        initComponents();
    }

    
    public void actualizarVista(Subject subject) {
        if (subject instanceof SalaSubject salaSubject) {
            actualizarDatosSala(salaSubject.getJugadores(), salaSubject.getNivel(), salaSubject.getLimiteJugadores());
            repaint();
            revalidate();
        }
    }
    
    public void actualizarDatosSala(List<JugadorSalaEsperaDTO> jugadores, TipoNivel nivel, int limiteJugadores) {
        panelListaJugadores.actualizarListaJugadores(jugadores, limiteJugadores);
        labelNivel.setText(nivel.toString());
    }

    public void configurarModoJugadorUnido() {
        btnAbandonarSala.setVisible(true);
        lblEspera.setVisible(true);
        btnSalir.setVisible(false);
        btnUnirme.setVisible(false);
    }

    public void configurarModoJugadorNoUnido() {
        btnSalir.setVisible(true);
        btnUnirme.setVisible(true);
        lblEspera.setVisible(false);
        btnAbandonarSala.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSala = new javax.swing.JLabel();
        panelListaJugadores = new vista.PanelListaJugadores();
        btnAbandonarSala = new javax.swing.JButton();
        lblNivel = new javax.swing.JLabel();
        labelNivel = new javax.swing.JLabel();
        lblEspera = new javax.swing.JLabel();
        btnUnirme = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 178, 0));

        lblSala.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblSala.setText("Sala");

        btnAbandonarSala.setBackground(new java.awt.Color(235, 91, 0));
        btnAbandonarSala.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAbandonarSala.setForeground(new java.awt.Color(255, 255, 255));
        btnAbandonarSala.setText("Abandonar Sala");
        btnAbandonarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarSalaActionPerformed(evt);
            }
        });

        lblNivel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNivel.setText("Nivel");

        labelNivel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNivel.setText("Básico");

        lblEspera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEspera.setText("Esperando a que inicice la partida...");

        btnUnirme.setBackground(new java.awt.Color(100, 13, 95));
        btnUnirme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUnirme.setForeground(new java.awt.Color(255, 255, 255));
        btnUnirme.setText("Unirme a la sala");
        btnUnirme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirmeActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(235, 91, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelListaJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNivel)
                                    .addComponent(labelNivel)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAbandonarSala)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                                .addComponent(btnSalir)
                                .addGap(168, 168, 168)
                                .addComponent(lblEspera))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(lblSala)))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(btnUnirme)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblSala)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panelListaJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblNivel)
                        .addGap(18, 18, 18)
                        .addComponent(labelNivel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnUnirme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbandonarSala)
                    .addComponent(lblEspera)
                    .addComponent(btnSalir))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbandonarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarSalaActionPerformed
        ControlesConfiguracionFactory controles = ControlesConfiguracionFactory.getInstance();
        controles.getControlAplicacion().abandonarSala();
    }//GEN-LAST:event_btnAbandonarSalaActionPerformed

    private void btnUnirmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirmeActionPerformed
        ControlesConfiguracionFactory controles = ControlesConfiguracionFactory.getInstance();
        controles.getControlAplicacion().unirseASala();
    }//GEN-LAST:event_btnUnirmeActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        ControlesConfiguracionFactory controles = ControlesConfiguracionFactory.getInstance();
        controles.getControlAplicacion().salir();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonarSala;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUnirme;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JLabel lblEspera;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblSala;
    private vista.PanelListaJugadores panelListaJugadores;
    // End of variables declaration//GEN-END:variables
}
